#!/bin/sh
if mountpoint -q /target; then
	echo "Installing consulfs to /target"
	cp ./main /target/consulfs
else
	echo "/target is not a mountpoint."
	echo "You can either:"
	echo "- re-run this container with -v /usr/local/bin:/target"
	echo "- extract the consulfs binary (located at ./main)"
fi
